apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pgadmin4
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: pgadmin4
spec:
  source:
    git:
      url: https://github.com/VikyaSurve/pgadmin4
      ref:
        branch: master
